import Head from 'next/head'
import Image from 'next/image'
import PokemonCard from '../components/PokemonCard';
import styles from '../styles/Home.module.css'

function Home({ data, results }) {
  const pokemon = results;

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the pokedex
        </h1>

        <div className={styles.grid}>
          {pokemon && pokemon.map((pokemon) => {
            return <PokemonCard key={pokemon.name} pokemon={pokemon} />
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/`);
  const data = await res.json();

  let results = data.results.map(async (e) => {
    const res = await fetch(e.url)
    return await res.json();
  });
  results  = await Promise.all(results);
  
  console.log('data = ', data);
  console.log('results = ', results);

  // Pass data to the page via props
  return { props: { data, results } }
}

export default Home